### ISSUE TITLE
ns1.rest.data.Source.update() fails due to missing field

### ISSUE THREAD

**Issue by namachieli** [ns1/ns1-python#17]
## Summary
The method `update()` in `ns1.rest.data.Source()` fails to complete due to the error:
```
ns1.rest.errors.ResourceException: server error, status code: 400: Input validation failed (Required field 'sourcetype' is missing)
```

## Details

In looking at [update()](https://github.com/ns1/ns1-python/blob/0129320eeb0864f93114ca3a920448756ea34b95/ns1/rest/data.py#L37) it appears only `sourceid` is required. 
In comparable methods in other modules (`records.py`, `zones.py`), the `update()` method requires the same required fields as the `create()` method, but not here.

Python `2.7.12`
ns1-python `0.9.19`

#### Full Error
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/data.py", line 46, in update
    errback=errback)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/resource.py", line 73, in _make_request
    return self._transport.send(type, self._make_url(path), **kwargs)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/transport/basic.py", line 88, in send
    handleProblem(resp.code, resp, body)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/transport/basic.py", line 77, in handleProblem
    body=msg)
ns1.rest.errors.ResourceException: server error, status code: 400: Input validation failed (Required field 'sourcetype' is missing)
```

## Reproduce
To reproduce this, take the following steps:
* install `ns1-python`
```bash
pip install ns1-python==0.9.19
```
* in python, do the following (setup, create source, update source)
```python
from ns1 import NS1
from ns1.rest.data import Source
ns1base = NS1(apiKey='APIKey')
sourcetype = 'nsone_v1'
name = 'test_source'
new_name = 'new_test_source'
source = Source(ns1base.config)
result = source.create(name=name, sourcetype=sourcetype)
print result
sourceid = 'NEWSOURCEID'
result = source.update(sourceid=sourceid, name=new_name)
```

## Troubleshooting

I have tried a few things to try to positively identify what needs to change, but i have been unsuccessful.

* Add `sourcetype=sourcetype` as a kwarg to `source.update()`
* Modify `ns1.rest.data.py.Source.update()` 
  - From
```python
def update(self, sourceid, callback=None, errback=None, **kwargs):
    body = {
        'id': sourceid
    }
    self._buildStdBody(body, kwargs)
    return self._make_request('POST',
                              '%s/%s' % (self.ROOT, sourceid),
                              body=body,
                              callback=callback,
                              errback=errback)
```
    - To (many variations as well)
```python
def update(self, sourceid, name, sourcetype, callback=None, errback=None, **kwargs):
    body = {
        'name': name,
        'sourcetype': sourcetype,
        'id': sourceid
    }
    self._buildStdBody(body, kwargs)
    return self._make_request('POST',
                              '%s/%s' % (self.ROOT, sourceid),
                              body=body,
                              callback=callback,
                              errback=errback)
```
## Expected Results
When running `source.update()`, the data source should be updated according to the fields passed.

## Complete Failure Example
```python
Python 2.7.12 (default, Nov 12 2018, 14:36:49)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from ns1 import NS1
>>> from ns1.rest.data import Source
>>> ns1base = NS1(apiKey='APIKEY')
>>> sourcetype='nsone_v1'
>>> name='test_source'
>>> new_name='new_test_source'
>>> source = Source(ns1base.config)
>>> result = source.create(name=name, sourcetype=sourcetype)
>>> print result
{u'status': u'ok', u'sourcetype': u'nsone_v1', u'feeds': [], u'config': {}, u'id': u'e25f39d7369c6d5030dec5f3ebb8b366', u'name': u'test_source'}
>>> sourceid='e25f39d7369c6d5030dec5f3ebb8b366'
>>> result = source.update(sourceid=sourceid, name=new_name)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/data.py", line 46, in update
    errback=errback)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/resource.py", line 73, in _make_request
    return self._transport.send(type, self._make_url(path), **kwargs)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/transport/basic.py", line 88, in send
    handleProblem(resp.code, resp, body)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/transport/basic.py", line 77, in handleProblem
    body=msg)
ns1.rest.errors.ResourceException: server error, status code: 400: Input validation failed (Required field 'sourcetype' is missing)
>>> result = source.update(sourceid=sourceid, name=new_name, sourcetype=sourcetype)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/data.py", line 46, in update
    errback=errback)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/resource.py", line 73, in _make_request
    return self._transport.send(type, self._make_url(path), **kwargs)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/transport/basic.py", line 88, in send
    handleProblem(resp.code, resp, body)
  File "/opt/stackstorm/virtualenvs/nsone/lib/python2.7/site-packages/ns1/rest/transport/basic.py", line 77, in handleProblem
    body=msg)
ns1.rest.errors.ResourceException: server error, status code: 400: Input validation failed (Required field 'sourcetype' is missing)
```

**Comment by mburtless** [comment]
Hi @namachieli - Thanks for the detailed reporting of this issue!

Given the error, I'd expect your updated `update` method shown above to resolve this problem.  I think the only change that may be needed there is to remove `id` field from the body (that's only required in the URL path according to https://ns1.com/api#post-modify-a-data-source). I think `sourcetype` field should also be removed, as that's not allowed to be updated.

I think we'll also need to add a kwarg to allow users to update the config details of the data source, but if we want to include that in a separate PR, and only have this fix allow users to update the name, I'd be fine with that.

If you get a chance to try that out and it seems to be working, feel free to open a PR.  Otherwise, I'll try to get this tested and patched shortly.

**Comment by rupa** [comment]
HI, we've merged a commit that should help with this. For now, you'll have to pass the `sourcetype` argument, although changing it is not supported, but at least you can change  `name` or `config` without errors. We should be pushing a new version to PyPi soon as well.

Feel free to reopen if you run into any issues.
